version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartcart-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - smartcart

  web:
    image: nginx:alpine
    container_name: smartcart-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - smartcart
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: smartcart-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - smartcart
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  redis:
    image: redis:alpine
    container_name: smartcart-redis
    restart: unless-stopped
    networks:
      - smartcart

  mailhog:
    image: mailhog/mailhog:latest
    container_name: smartcart-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - smartcart

networks:
  smartcart:
    driver: bridge

volumes:
  mysql-data:
    driver: local 